version: '3'
services:
  haproxy:
    build: .
    container_name: lb
    environment:
      - CERTS=aleyant.budega.club
      - EMAIL=psychopenguin@gmail.com
      - STAGING=false
    volumes:
      - '$PWD/data/letsencrypt:/etc/letsencrypt'
      - '$PWD/conf/haproxy.cfg:/etc/haproxy.cfg'
    networks:
      - alyantNet
    ports:
      - '80:80'
      - '443:443'
    image: 'docker-haproxy-certbot:latest'
  rsyslog:
    container_name: rsyslog
    environment:
      - TZ=UTC
      - ENV_VAR=121333
    volumes:
      - '$PWD/data/rsyslog/config:/config'
    networks:
      - alyantNet
    ports:
      - '514:514'
    image: 'rsyslog/syslog_appliance_alpine'
  back01: &default_backend
    container_name: lorem-ipsum-01
    networks:
      - alyantNet
    image: 'python:alpine'
    volumes:
      - '$PWD/web-server:/www'
    command: 'python -m http.server'
    working_dir: '/www'
    ports:
      - '8000'
  back02:
    <<: *default_backend
    container_name: lorem-ipsum-02
  back03:
    <<: *default_backend
    container_name: lorem-ipsum-03
networks:
  alyantNet:
    driver: bridge
